export const governorates = [
    "cairo",
    "giza",
    "alexandria",
    "dakahlia",
    "red sea",
    "beheira",
    "fayoum",
    "gharbiya",
    "ismailia",
    "menofia",
    "minya",
    "qalyubia",
    "new valley",
    "suez",
    "aswan",
    "assiut",
    "beni suef",
    "port said",
    "damietta",
    "sharkia",
    "south sinai",
    "kafr el sheikh",
    "matrouh",
    "luxor",
    "qena",
    "north sinai",
    "sohag"
];
